name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  #

      - name: Install dependencies
        run: pip install -r requirements.txt  #

      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: fmlin
          TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJDAwNGUwYjdkLTk2NTktNGZlMy04M2E2LTBhZDZmZTE1ODkxNAACKlszLCI2ZjNiOTRjMi02ZTJjLTRmODYtODIyYi1jYzhiYmExZjJlYmEiXQAABiCETyFhf7A_b-wwjfM8JOpG-EIQIOPXs7tiChqjYW3bVg
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
